[package]
name = "hdrsample"
version = "0.1.0"

description = "A port of HdrHistogram to Rust"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://jon.tsp.io/crates/hdrsample"
homepage = "https://github.com/jonhoo/hdrsample"
repository = "https://github.com/jonhoo/hdrsample.git"

keywords = ["sampling", "statistics", "analytics"]

license = "MIT/Apache-2.0"

[dependencies]
num = "0.1"
