[package]
name = "hdrsample"
version = "1.1.1"

description = "A port of HdrHistogram to Rust"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://jon.tsp.io/crates/hdrsample"
homepage = "https://github.com/jonhoo/hdrsample"
repository = "https://github.com/jonhoo/hdrsample.git"

keywords = ["sampling", "statistics", "analytics"]

license = "MIT/Apache-2.0"

[features]
benchmark = ["criterion"]
#benchmark = [] # for crates.io publication

[dependencies]
num = "0.1"
criterion = { git = "https://github.com/japaric/criterion.rs.git", optional = true }

[lib]

[[bin]]
name = "perf"
path = "benchmarks/all.rs"

[[bin]]
name = "busy"
path = "benchmarks/busy.rs"

[profile.release]
debug=true
