[package]
name = "hdrsample"
version = "3.0.0"

description = "A port of HdrHistogram to Rust"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/hdrsample"
homepage = "https://github.com/jonhoo/hdrsample"
repository = "https://github.com/jonhoo/hdrsample.git"

keywords = ["sampling", "statistics", "analytics"]
categories = ["data-structures", "development-tools::profiling"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/hdrsample" }

[features]
#benchmark = ["criterion"]
benchmark = [] # for crates.io publication
bench_private = [] # for enabling nightly-only feature(test) on the main crate to allow benchmarking private code

[dependencies]
num = "0.1"
byteorder = "1.0.0"
flate2 = "0.2.17"
#criterion = { git = "https://github.com/japaric/criterion.rs.git", optional = true }

[dev-dependencies]
rand = "0.3.15"

[lib]
path = "src/lib.rs"

[[bin]]
name = "perf"
path = "benchmarks/all.rs"

[[bin]]
name = "busy"
path = "benchmarks/busy.rs"

[profile.release]
debug=true

[profile.bench]
debug=true
